// DATABASE ERROR CODE
module.exports.PG_UNIQUE_EXIST = '23505';

// GENERAL ERROR CODE
exports.UPLOAD_ERROR = 'ERR_UPLOAD';
exports.FORM_INSUFFICIENT = 'ERR_FORM';

// PRODUCT
exports.PROD_IMG_PREFIX = 'PROD_';